import type { CatalogSong, CityMoment, JourneyNode, SongStory, TimeTravelDestination } from './types'

export const years = [1968, 1977, 1981, 1984, 1989, 1991, 1994, 2001]

export const cityMoments: CityMoment[] = [
  {
    id: 'warsaw-1981', city: 'Warsaw', country: 'Poland', year: 1981,
    summary: 'A city living between the energy of Solidarity and the shock of martial law—where radio, records, festivals, and unofficial exchange carried sounds through political pressure.',
    genres: ['Polish rock', 'new wave', 'post-punk'], artists: ['Maanam', 'Perfect', 'Brygada Kryzys'], songs: ['Boskie Buenos', 'Chcemy być sobą', 'Centrala'],
    youthCulture: 'Concerts, student clubs, record exchanges, magazines and cassette circulation helped younger listeners construct a cultural life that was never reducible to official media.',
    politicalContext: 'Solidarity had become a mass social movement. Martial law was declared on 13 December 1981, bringing arrests, restrictions, censorship and a transformed public sphere.',
    censorshipContext: 'Lyrics, broadcasts and performances operated within state censorship. Restrictions changed over time and artists used metaphor, ambiguity and live culture to navigate them.',
    culturalMood: 'Compressed, inventive and alert: public constraint beside a vivid desire for cultural autonomy.',
    mediaAccess: 'State radio and television remained central, while Radio Free Europe, imported records, copied tapes and personal networks widened the listening field.',
    image: '/images/warsaw-1981.png',
    sources: ['European Solidarity Centre', 'POLIN Museum of the History of Polish Jews', 'Polish Radio archive']
  },
  {
    id: 'berlin-1989', city: 'Berlin', country: 'Germany', year: 1989,
    summary: 'Two music ecosystems separated by a wall entered a sudden, unfinished conversation as borders opened and abandoned spaces began to acquire new cultural possibilities.',
    genres: ['electronic', 'industrial', 'punk'], artists: ['David Bowie', 'Einstürzende Neubauten', 'Die Anderen'], songs: ['Heroes'],
    youthCulture: 'Clubs, squats, punk scenes and experimental art offered different forms of belonging on both sides of the city.',
    politicalContext: 'Mass demonstrations and political crisis in East Germany culminated in the opening of the Berlin Wall on 9 November 1989.',
    censorshipContext: 'East German cultural production was licensed and monitored; unofficial scenes still formed around churches, private spaces and semi-legal performance networks.',
    culturalMood: 'Disbelief, velocity and possibility—the sense that familiar boundaries had become negotiable overnight.',
    mediaAccess: 'West Berlin had commercial abundance; many East Berliners could receive Western broadcasts, though access, ownership and cultural permission remained unequal.',
    image: '/images/berlin-1989.png',
    sources: ['Haus der Geschichte', 'DDR Museum', 'Berlin Wall Memorial']
  },
  {
    id: 'london-1977', city: 'London', country: 'United Kingdom', year: 1977,
    summary: 'Punk compressed economic frustration, provocation, fashion and do-it-yourself culture into a scene that challenged the institutions around popular music.',
    genres: ['punk', 'reggae', 'pub rock'], artists: ['The Clash', 'Sex Pistols', 'X-Ray Spex'], songs: ['London Calling'],
    youthCulture: 'Independent labels, fanzines, record shops and small venues made participation feel possible without institutional permission.',
    politicalContext: 'Britain faced inflation, unemployment, industrial conflict and intense debate over race, class and national decline.',
    censorshipContext: 'Pressure came through broadcasters, venues, retailers and public controversy rather than a single state censorship system.',
    culturalMood: 'Confrontational, inventive and impatient.', mediaAccess: 'A dense music press, national radio, shops, labels and live venues accelerated the scene.',
    sources: ['British Library', 'Museum of London', 'Victoria and Albert Museum']
  },
  {
    id: 'new-york-1979', city: 'New York', country: 'United States', year: 1979,
    summary: 'Disco, punk and a still-emerging hip-hop culture overlapped across boroughs and radically different social worlds.',
    genres: ['hip-hop', 'disco', 'punk'], artists: ['Grandmaster Flash', 'Chic', 'Ramones'], songs: ['Rapper’s Delight'],
    youthCulture: 'Block parties, clubs, community centers, downtown venues and record shops formed parallel infrastructures of invention.',
    politicalContext: 'The city was rebuilding after fiscal crisis while neighborhoods faced disinvestment and unequal public services.',
    censorshipContext: 'The decisive barriers were commercial access, gatekeeping and structural inequality rather than formal state censorship.',
    culturalMood: 'Resourceful, fragmented and future-facing.', mediaAccess: 'Local radio, clubs, live performance and early recordings moved sounds between communities.',
    sources: ['Smithsonian NMAAHC', 'Museum of the City of New York', 'Library of Congress']
  },
  {
    id: 'moscow-1991', city: 'Moscow', country: 'Soviet Union / Russia', year: 1991,
    summary: 'A year of political rupture in which rock culture, imported media and newly commercial forms met the collapse of familiar institutions.',
    genres: ['Russian rock', 'new wave', 'heavy metal'], artists: ['Kino', 'DDT', 'Aquarium'], songs: ['Peremen!'],
    youthCulture: 'Rock clubs and tape exchange had helped build alternative publics before the market transformed how music circulated.',
    politicalContext: 'The failed August coup accelerated the dissolution of the Soviet Union in December 1991.',
    censorshipContext: 'Glasnost had already loosened earlier controls, but the transition brought new uncertainty rather than a simple move from restriction to freedom.',
    culturalMood: 'Expansive, disorienting and economically precarious.', mediaAccess: 'Imported recordings and new broadcast formats expanded rapidly but unevenly.',
    sources: ['Wilson Center Digital Archive', 'Garage Museum of Contemporary Art', 'BBC Archive']
  },
  {
    id: 'paris-1968', city: 'Paris', country: 'France', year: 1968,
    summary: 'Student occupation, mass strikes, political posters and chanson made sound part of a broader contest over authority and everyday life.',
    genres: ['chanson', 'rock', 'protest song'], artists: ['Léo Ferré', 'Jacques Dutronc'], songs: ['Paris Mai'],
    youthCulture: 'Universities, cinemas, cafés and street committees became spaces where art and politics mixed.',
    politicalContext: 'Student protest expanded into a national general strike and a crisis for the government of Charles de Gaulle.',
    censorshipContext: 'Broadcast control and political pressure shaped coverage, while posters and independent print multiplied in the streets.',
    culturalMood: 'Argumentative, utopian and volatile.', mediaAccess: 'Radio, records, cinema and an explosion of print connected events to a wider public.',
    sources: ['Bibliothèque nationale de France', 'Institut national de l’audiovisuel', 'Musée Carnavalet']
  }
]

export const travelDestinations: TimeTravelDestination[] = [
  { id:'berlin-moscow', sourceId:'berlin-1989', destinationType:'city', destinationId:'moscow-1991', city:'Moscow', country:'Russia', year:1991, connectionType:'POLITICAL PARALLEL', connectionExplanation:'Follow another music culture through the collapse of an old political order.' },
  { id:'london-warsaw', sourceId:'london-1977', destinationType:'city', destinationId:'warsaw-1981', city:'Warsaw', country:'Poland', year:1982, connectionType:'CROSS-BORDER INFLUENCE', connectionExplanation:'See how punk was adapted inside a very different system of media, access and power.' },
  { id:'newyork-paris', sourceId:'new-york-1979', destinationType:'city', destinationId:'paris-1968', city:'Paris', country:'France', year:1990, connectionType:'MUSICAL MIGRATION', connectionExplanation:'Trace how hip-hop crossed the Atlantic and was remade through another language and urban history.' },
  { id:'manchester-warsaw', sourceId:'berlin-1989', destinationType:'city', destinationId:'warsaw-1981', city:'Warsaw', country:'Poland', year:1985, connectionType:'SHARED GENRE', connectionExplanation:'Follow post-punk into a scene shaped by censorship and limited Western media access.' }
]

export const heroesSong: SongStory = {
  id:'heroes-1977', title:'Heroes', artist:'David Bowie', year:1977, country:'United Kingdom / West Germany', genre:'Art rock',
  summary:'Recorded in West Berlin, “Heroes” turned a private, fragile act of defiance into one of the most enduring musical images associated with a divided city.',
  themes:['intimacy under pressure','temporary freedom','division','memory'],
  historicalContext:'Berlin remained physically and politically divided. Bowie worked at Hansa Studio, close to the Wall, during a period when the city carried both Cold War tension and an unusually open experimental culture in the West.',
  culturalContext:'The song’s later association with the fall of the Wall can obscure its earlier life. Its historical power lies partly in how later listeners attached a public memory of division to a deliberately ambiguous personal narrative.',
  sound:'A slowly intensifying arrangement, sustained guitar textures and a vocal performance that becomes more forceful as the song develops create the feeling of possibility pushing against constraint.',
  impact:'The Berlin recordings became central to Bowie’s artistic legacy and to the mythology of late-1970s Berlin as a space of experimentation, exile and reinvention.',
  then:'Released as a single in 1977, it was respected but not initially a major UK chart hit. Its cultural status grew through performance, reissue and its connection to Berlin memory.',
  now:'It is often heard as an anthem of resilience and political possibility, especially in accounts of divided Berlin—an interpretation larger and more public than its initial reception.',
  spotifyUrl:'https://open.spotify.com/track/7Jh1bpe76CNTCgdgAdBw4Z', spotifyUri:'spotify:track:7Jh1bpe76CNTCgdgAdBw4Z',
  youtubeVideoId:'lXgkuM2NhYI', youtubeUrl:'https://www.youtube.com/watch?v=lXgkuM2NhYI', videoType:'OFFICIAL VIDEO', videoTitle:'David Bowie — Heroes', videoSourceLabel:'David Bowie',
  sources:['David Bowie official archive','Victoria and Albert Museum','Berlin Wall Memorial'],
  relatedTimeTravelDestinations:[travelDestinations[0], travelDestinations[3]]
}

const links = (artist:string,title:string) => ({
  spotifyUrl:`https://open.spotify.com/search/${encodeURIComponent(`${artist} ${title}`)}`,
  youtubeUrl:`https://www.youtube.com/results?search_query=${encodeURIComponent(`${artist} ${title} official video`)}`
})

const destinations = (sourceId:string):TimeTravelDestination[] => travelDestinations.filter(d=>d.sourceId===sourceId).slice(0,2)

export const musicCatalog: CatalogSong[] = [
  {id:'street-fighting-man-1968',title:'Street Fighting Man',artist:'The Rolling Stones',year:1968,decade:1960,country:'United Kingdom',city:'London',genre:'Rock',archiveLabel:'PROTEST / STREET POLITICS',accent:'red',summary:'A tense rock single released into a year of demonstrations, upheaval and televised conflict.',themes:['street protest','political frustration','spectatorship'],historicalContext:'The song arrived in 1968, a year marked by anti-war demonstrations, student revolt and political violence across several countries.',culturalContext:'Its meaning comes partly from the distance between revolutionary imagery and the position of a famous British rock band observing unrest.',sound:'Acoustic guitars recorded with unusual density, hard percussion and a compressed, urgent arrangement.',impact:'It became one of rock’s best-known attempts to confront the protest politics of 1968.',then:'Some broadcasters and stations treated the single cautiously amid fears that popular music could intensify unrest.',now:'It is heard both as a protest anthem and as an ambiguous record of rock stars negotiating political upheaval.',artistContext:'By 1968 the Rolling Stones were moving from pop stardom toward a darker, more confrontational public identity.',lyricsMeaning:'The narrator is pulled toward street rebellion but also recognizes the limits of performance and personal power.',politicalMoment:'Vietnam War protest, student movements and urban unrest made the language of revolution part of everyday media.',sources:['British Library','Rock & Roll Hall of Fame'],relatedTimeTravelDestinations:destinations('london-1977'),...links('The Rolling Stones','Street Fighting Man')},
  {id:'revolution-1968',title:'Revolution',artist:'The Beatles',year:1968,decade:1960,country:'United Kingdom',city:'London',genre:'Rock',archiveLabel:'COUNTERCULTURE / DEBATE',accent:'cream',summary:'A song arguing with the revolutionary certainty surrounding the politics of 1968.',themes:['revolution','doubt','political responsibility'],historicalContext:'It was released during a year of protest movements, the Prague Spring and its suppression, the Vietnam War and conflict inside the counterculture.',culturalContext:'The song frustrated listeners who wanted a simple endorsement of revolution because it questioned methods as much as goals.',sound:'Distorted guitars and a direct, almost live attack turn a political argument into compact rock.',impact:'It became a lasting example of a major pop group entering public political debate.',then:'Responses divided along the same fault lines present in the movement politics of the period.',now:'It remains useful precisely because its caution, privilege and uncertainty are still open to criticism.',artistContext:'The Beatles were global cultural figures whose political statements carried unusual reach and scrutiny.',lyricsMeaning:'The lyric supports change while resisting violence and ideological certainty; its ambivalence is the central point.',politicalMoment:'Young people were debating reform, revolution, war and state violence in public and in music.',sources:['The Beatles official archive','British Library'],relatedTimeTravelDestinations:[],...links('The Beatles','Revolution')},
  {id:'say-it-loud-1968',title:'Say It Loud – I’m Black and I’m Proud',artist:'James Brown',year:1968,decade:1960,country:'United States',city:'New York',genre:'Funk / soul',archiveLabel:'CIVIL RIGHTS / IDENTITY',accent:'orange',summary:'A declaration of Black pride that moved a political slogan into the center of popular music.',themes:['Black pride','self-definition','collective voice'],historicalContext:'Released months after the assassination of Martin Luther King Jr., during a turning point in civil-rights and Black Power politics.',culturalContext:'Its call-and-response structure made identity public, participatory and impossible to treat as background.',sound:'A clipped funk groove, children’s chorus and commanding vocal performance.',impact:'It helped normalize explicit Black pride in mainstream popular music.',then:'The record was celebrated by many listeners and contested by others who heard its language as confrontational.',now:'Its slogan remains culturally legible, though later generations have debated the politics and limits of celebrity representation.',artistContext:'James Brown was both an entertainment institution and an increasingly visible figure in debates about Black politics and economic power.',lyricsMeaning:'The words reject shame and insist that Black identity be spoken collectively and with pride.',politicalMoment:'Civil-rights gains coexisted with segregation, police violence, urban inequality and a growing Black Power movement.',sources:['Smithsonian NMAAHC','Library of Congress'],relatedTimeTravelDestinations:[],...links('James Brown',"Say It Loud I'm Black and I'm Proud")},
  {id:'gyongyhaju-lany-1969',title:'Gyöngyhajú lány',artist:'Omega',year:1969,decade:1960,country:'Hungary',city:'Budapest',genre:'Progressive rock',archiveLabel:'EASTERN BLOC / CROSS-BORDER HIT',accent:'blue',summary:'A Hungarian rock ballad that became one of the Eastern Bloc’s most durable cross-border recordings.',themes:['dream','longing','memory'],historicalContext:'Hungarian popular culture operated within a state-socialist media system that allowed some Western-influenced music while regulating access and careers.',culturalContext:'Its afterlife shows how a song in a less globally dominant language can travel through covers, radio, sampling and memory.',sound:'Melodic psychedelic rock with organ, spacious guitar and a dramatic vocal line.',impact:'The song circulated widely across Central and Eastern Europe and gained a long international afterlife.',then:'It demonstrated that rock made behind the Iron Curtain could command audiences beyond its home market.',now:'It is remembered as both a regional classic and a recurring source for later reinterpretation.',artistContext:'Omega became one of Hungary’s most internationally visible rock groups.',lyricsMeaning:'The pearl-haired girl functions as a dream figure—part romance, part memory, part unreachable world.',politicalMoment:'Cultural policy balanced limited openness with institutional control over recording, touring and publication.',sources:['Hungarian National Museum','Fortepan archive'],relatedTimeTravelDestinations:[],...links('Omega','Gyöngyhajú lány')},
  {id:'revolution-not-televised-1971',title:'The Revolution Will Not Be Televised',artist:'Gil Scott-Heron',year:1971,decade:1970,country:'United States',city:'New York',genre:'Spoken word / jazz',archiveLabel:'MEDIA / REVOLUTION',accent:'red',summary:'A compressed critique of consumer media and passive spectatorship.',themes:['media','revolution','consumer culture'],historicalContext:'The recording emerged after the high point of 1960s movement politics, amid continuing struggles over race, policing, war and economic inequality.',culturalContext:'Its references were highly specific to American television and advertising, yet its central argument travelled far beyond them.',sound:'Spoken delivery over an insistent jazz-funk ensemble makes political language rhythmic without turning it into a conventional song.',impact:'It became foundational to later spoken-word and hip-hop traditions.',then:'Listeners encountered it as both cultural criticism and an extension of Black radical poetics.',now:'The phrase is repeatedly reused in new media environments, sometimes detached from its original critique.',artistContext:'Scott-Heron connected poetry, music and journalism in work focused on Black life and American power.',lyricsMeaning:'Real political transformation cannot be consumed as entertainment; it requires presence and participation.',politicalMoment:'Post–civil rights America was confronting the gap between legal change and structural inequality.',sources:['Smithsonian NMAAHC','Library of Congress'],relatedTimeTravelDestinations:destinations('new-york-1979'),...links('Gil Scott-Heron','The Revolution Will Not Be Televised')},
  {id:'get-up-stand-up-1973',title:'Get Up, Stand Up',artist:'The Wailers',year:1973,decade:1970,country:'Jamaica',city:'Kingston',genre:'Reggae',archiveLabel:'RIGHTS / POSTCOLONIAL VOICE',accent:'olive',summary:'A concise demand for dignity and political agency that became a global protest standard.',themes:['rights','agency','resistance'],historicalContext:'Jamaica’s post-independence politics were shaped by inequality, party conflict and a music industry with growing international reach.',culturalContext:'Rastafari, anti-colonial thought and Jamaican vernacular give the song meanings that generic “protest anthem” labels can flatten.',sound:'A heavy reggae pulse leaves space for repeated, collective vocal phrases.',impact:'It became one of the most frequently reused musical calls for resistance.',then:'International listeners often received it through the growing global market for reggae.',now:'It survives as a flexible protest song, though its specific Jamaican and Rastafarian contexts still matter.',artistContext:'Bob Marley and Peter Tosh were bringing Jamaican political and spiritual language to a rapidly expanding audience.',lyricsMeaning:'The words reject waiting for justice to arrive from religious or political authority and demand action in the present.',politicalMoment:'Postcolonial sovereignty had not removed economic hierarchy or social conflict.',sources:['Bob Marley Museum','National Library of Jamaica'],relatedTimeTravelDestinations:[],...links('The Wailers','Get Up Stand Up')},
  {id:'radioactivity-1975',title:'Radioactivity',artist:'Kraftwerk',year:1975,decade:1970,country:'West Germany',city:'Düsseldorf',genre:'Electronic',archiveLabel:'TECHNOLOGY / MODERNITY',accent:'blue',summary:'A minimal electronic meditation whose meaning shifted as nuclear politics changed.',themes:['radio','nuclear power','technology'],historicalContext:'Nuclear energy, broadcasting and technological modernity were active political and cultural questions in 1970s Europe.',culturalContext:'The title’s double meaning—radio activity and radioactivity—allowed the song’s politics to evolve across performances and versions.',sound:'Synthetic pulse, coded voices and austere melody treat the studio as the main instrument.',impact:'It helped establish a visual and sonic grammar that shaped electronic music internationally.',then:'Its original ambiguity was central to its modernist effect.',now:'Later performances made anti-nuclear meanings more explicit, changing how audiences hear the original.',artistContext:'Kraftwerk developed a deliberately controlled image of European technological modernity.',lyricsMeaning:'The lyric links transmission and contamination, fascination and danger, without resolving them into a simple message.',politicalMoment:'Anti-nuclear movements were expanding while governments promoted atomic energy as progress.',sources:['Kraftwerk official archive','Deutsches Museum'],relatedTimeTravelDestinations:[],...links('Kraftwerk','Radioactivity')},
  {id:'zombie-1976',title:'Zombie',artist:'Fela Kuti',year:1976,decade:1970,country:'Nigeria',city:'Lagos',genre:'Afrobeat',archiveLabel:'MILITARY POWER / SATIRE',accent:'orange',summary:'A long, dance-driven satire of unquestioning military obedience.',themes:['militarism','obedience','state violence'],historicalContext:'Nigeria was governed by military regimes, and Fela’s commune and performances were under intense state scrutiny.',culturalContext:'The song’s force lies in its combination of ridicule, Yoruba-inflected performance, pidgin English and extended dance music.',sound:'Layered horns, guitars, percussion and call-and-response accumulate pressure over an extended groove.',impact:'It became inseparable from the violent state retaliation against Fela’s Kalakuta Republic.',then:'Its satire was immediately recognizable and politically dangerous.',now:'It remains a reference point for artists confronting authoritarianism and military power.',artistContext:'Fela Kuti made music, performance space and everyday life part of one political project.',lyricsMeaning:'Soldiers are described as moving without independent thought; repetition turns military discipline into absurdity.',politicalMoment:'Military rule narrowed the space for dissent while music offered a mass public platform.',sources:['Fela Kuti official archive','Smithsonian Folkways'],relatedTimeTravelDestinations:[],...links('Fela Kuti','Zombie')},
  {id:'god-save-queen-1977',title:'God Save the Queen',artist:'Sex Pistols',year:1977,decade:1970,country:'United Kingdom',city:'London',genre:'Punk',archiveLabel:'MONARCHY / YOUTH ANGER',accent:'red',summary:'A punk single timed to Britain’s Silver Jubilee that turned national ceremony into confrontation.',themes:['monarchy','alienation','national identity'],historicalContext:'The Jubilee presented national continuity while unemployment and economic conflict shaped many young people’s lives.',culturalContext:'Its provocation worked through tabloids, visual design, performance and broadcast controversy as much as the recording itself.',sound:'Dense guitars, shouted vocals and a compact structure designed for maximum public friction.',impact:'It fixed punk in the popular imagination as a political and media event.',then:'Major broadcasters restricted it, while controversy amplified its reach.',now:'It is simultaneously archive object, commodity and still-effective insult to official national narratives.',artistContext:'The Sex Pistols were a short-lived group whose management, fashion network and press conflicts became part of the work.',lyricsMeaning:'The song attacks a national system it presents as offering no future to the young.',politicalMoment:'Economic decline and Jubilee spectacle exposed competing visions of Britain.',sources:['British Library','Victoria and Albert Museum'],relatedTimeTravelDestinations:destinations('london-1977'),...links('Sex Pistols','God Save the Queen')},
  {id:'heroes-1977',title:'Heroes',artist:'David Bowie',year:1977,decade:1970,country:'United Kingdom / West Germany',city:'Berlin',genre:'Art rock',archiveLabel:'DIVIDED CITY / MEMORY',accent:'blue',summary:heroesSong.summary,themes:heroesSong.themes,historicalContext:heroesSong.historicalContext,culturalContext:heroesSong.culturalContext,sound:heroesSong.sound,impact:heroesSong.impact,then:heroesSong.then,now:heroesSong.now,artistContext:'Bowie used West Berlin as a place of artistic reset, working near a border that structured everyday life.',lyricsMeaning:'A private, temporary act of intimacy becomes a fantasy of freedom against physical division.',politicalMoment:'The Cold War division of Berlin shaped geography, media and cultural mythology.',sources:heroesSong.sources,relatedTimeTravelDestinations:heroesSong.relatedTimeTravelDestinations,spotifyUrl:heroesSong.spotifyUrl,spotifyUri:heroesSong.spotifyUri,youtubeUrl:heroesSong.youtubeUrl,youtubeVideoId:heroesSong.youtubeVideoId,videoType:heroesSong.videoType,videoTitle:heroesSong.videoTitle,videoSourceLabel:heroesSong.videoSourceLabel},
  {id:'soweto-blues-1977',title:'Soweto Blues',artist:'Miriam Makeba',year:1977,decade:1970,country:'South Africa',city:'Johannesburg',genre:'Afro-pop / protest',archiveLabel:'APARTHEID / EXILE',accent:'olive',summary:'A musical account of the Soweto uprising written from exile.',themes:['apartheid','state violence','mourning'],historicalContext:'In June 1976, police attacked students protesting compulsory Afrikaans instruction; the uprising became a turning point in resistance to apartheid.',culturalContext:'Makeba’s exile gave the recording an international platform while separating the singer from the country she described.',sound:'A buoyant arrangement carries a narrative of grief and political accusation.',impact:'It helped make the Soweto uprising audible to audiences outside South Africa.',then:'The song circulated internationally while anti-apartheid organizing expanded.',now:'It remains both testimony and an entry into the cultural work of South African exiles.',artistContext:'Miriam Makeba used global celebrity to oppose apartheid and represent South African music abroad.',lyricsMeaning:'The song narrates how language policy, student protest and police violence transformed Soweto.',politicalMoment:'Apartheid regulated movement, education, language and political participation through state violence.',sources:['South African History Archive','Miriam Makeba Foundation'],relatedTimeTravelDestinations:[],...links('Miriam Makeba','Soweto Blues')},
  {id:'good-times-1979',title:'Good Times',artist:'Chic',year:1979,decade:1970,country:'United States',city:'New York',genre:'Disco',archiveLabel:'DISCO / ECONOMIC ANXIETY',accent:'cream',summary:'An immaculate dance record whose optimism sits beside recession-era pressure.',themes:['escape','pleasure','economic uncertainty'],historicalContext:'The end of the 1970s brought inflation, urban inequality and a backlash against disco’s Black, Latino and queer roots.',culturalContext:'The bass line became a bridge between disco and early recorded hip-hop.',sound:'Interlocking bass, guitar, strings and controlled vocals turn precision into collective pleasure.',impact:'Its groove became foundational source material for “Rapper’s Delight” and later dance music.',then:'It was a major hit during the peak and backlash of disco culture.',now:'It is heard as both pop craft and a key junction in the genealogy of hip-hop.',artistContext:'Nile Rodgers and Bernard Edwards designed Chic as a sophisticated, self-aware dance-music project.',lyricsMeaning:'The promise of good times works as celebration, denial and survival against economic instability.',politicalMoment:'Public hostility to disco often carried racial, sexual and class meanings beyond musical taste.',sources:['Smithsonian NMAAHC','Museum of the City of New York'],relatedTimeTravelDestinations:destinations('new-york-1979'),...links('Chic','Good Times')},
  {id:'rappers-delight-1979',title:'Rapper’s Delight',artist:'The Sugarhill Gang',year:1979,decade:1970,country:'United States',city:'New York',genre:'Hip-hop',archiveLabel:'HIP-HOP / RECORDED BREAKTHROUGH',accent:'orange',summary:'The commercial single that introduced many listeners outside New York to rapping.',themes:['performance','bragging','party culture'],historicalContext:'Hip-hop had developed through Bronx block parties, DJs, MCs and community spaces before the record industry understood it.',culturalContext:'Its success widened access while raising lasting questions about ownership, authenticity and who benefited from recording a live culture.',sound:'Extended rapping over a recreated version of Chic’s “Good Times” groove.',impact:'It made recorded hip-hop commercially visible around the world.',then:'Many scene participants saw it as both breakthrough and imperfect representation.',now:'It is remembered as a gateway record rather than the beginning of hip-hop itself.',artistContext:'The group was assembled for recording rather than emerging as the central crew of the Bronx scene.',lyricsMeaning:'The words display verbal skill, personality and social energy more than a single narrative argument.',politicalMoment:'Urban disinvestment formed the background to a culture built through reused technology and local organization.',sources:['Smithsonian NMAAHC','Universal Hip Hop Museum'],relatedTimeTravelDestinations:destinations('new-york-1979'),...links('The Sugarhill Gang',"Rapper's Delight")},
  {id:'boskie-buenos-1981',title:'Boskie Buenos',artist:'Maanam',year:1981,decade:1980,country:'Poland',city:'Warsaw',genre:'New wave / rock',archiveLabel:'POLISH ROCK / NEW WAVE',accent:'red',summary:'A sharp, theatrical recording from the breakthrough years of Polish new wave.',themes:['desire','escape','stylized modernity'],historicalContext:'Poland in 1981 moved from the mass energy of Solidarity into martial law in December.',culturalContext:'Polish rock audiences heard local language and modern style inside a media system still shaped by censorship and official institutions.',sound:'Angular guitar, insistent rhythm and Kora’s highly controlled vocal performance.',impact:'It helped establish Maanam as one of the defining Polish bands of the 1980s.',then:'The song belonged to a rapidly expanding Polish rock audience before martial law transformed public culture.',now:'It remains a vivid marker of the period’s modernity rather than merely a nostalgic hit.',artistContext:'Maanam combined art-rock background, new-wave economy and Kora’s singular lyrical presence.',lyricsMeaning:'The words use travel, fantasy and sensual imagery rather than direct political declaration; that distance from literal politics is part of their appeal.',politicalMoment:'Solidarity, censorship, scarcity and martial law shaped how music was produced and heard.',sources:['Polish Radio archive','European Solidarity Centre'],relatedTimeTravelDestinations:destinations('london-1977'),...links('Maanam','Boskie Buenos')},
  {id:'chcemy-byc-soba-1981',title:'Chcemy być sobą',artist:'Perfect',year:1981,decade:1980,country:'Poland',city:'Warsaw',genre:'Rock',archiveLabel:'IDENTITY / PUBLIC CHANT',accent:'cream',summary:'A Polish rock song whose refrain became larger than its original text in public performance.',themes:['identity','autonomy','collective voice'],historicalContext:'It emerged during the Solidarity period, when demands for social and cultural autonomy were unusually visible.',culturalContext:'Audiences transformed the refrain through collective singing, showing how reception can politicize a song beyond authorial intention.',sound:'Direct guitar rock built around a refrain designed for a crowd.',impact:'It became one of the most durable audience-participation songs in Polish rock.',then:'Concert audiences could hear the demand to “be ourselves” as a statement about public life.',now:'It is remembered through both political memory and the broad universality of its refrain.',artistContext:'Perfect became a central mainstream Polish rock group at the moment the genre’s audience expanded dramatically.',lyricsMeaning:'The lyric centers personal and collective autonomy; context made that wish sound political.',politicalMoment:'A mass social movement challenged the ruling system before martial law narrowed public space.',sources:['Polish Radio archive','National Centre for Culture Poland'],relatedTimeTravelDestinations:[],...links('Perfect','Chcemy być sobą')},
  {id:'centrala-1982',title:'Centrala',artist:'Brygada Kryzys',year:1982,decade:1980,country:'Poland',city:'Warsaw',genre:'Post-punk',archiveLabel:'UNDERGROUND / SYSTEM',accent:'blue',summary:'A cold, repetitive post-punk vision of systems, signals and centralized power.',themes:['control','alienation','system'],historicalContext:'Recorded around the period of martial law, when communication, movement and public assembly were heavily constrained.',culturalContext:'Its language is indirect enough to remain art, but the atmosphere of institutional control was impossible to miss.',sound:'Dub-informed bass, clipped guitar and repetition create a mechanical urban pressure.',impact:'The album became a canonical document of Polish post-punk.',then:'It spoke to listeners living through a highly controlled political environment without functioning as a literal news report.',now:'Its central metaphor travels easily into digital systems and contemporary surveillance culture.',artistContext:'Brygada Kryzys connected punk, reggae and post-punk within Warsaw’s alternative scene.',lyricsMeaning:'“The central” can be heard as institution, communication hub or abstract power that organizes life from elsewhere.',politicalMoment:'Martial law placed media, telephones, travel and association under exceptional control.',sources:['Polish Radio archive','Museum of Warsaw'],relatedTimeTravelDestinations:destinations('london-1977'),...links('Brygada Kryzys','Centrala')},
  {id:'the-message-1982',title:'The Message',artist:'Grandmaster Flash and the Furious Five',year:1982,decade:1980,country:'United States',city:'New York',genre:'Hip-hop',archiveLabel:'URBAN CRISIS / REPORTAGE',accent:'orange',summary:'A detailed portrait of pressure, disinvestment and psychological strain in the city.',themes:['poverty','urban life','mental pressure'],historicalContext:'New York’s poorest neighborhoods lived with the aftereffects of fiscal crisis, housing abandonment and reduced public investment.',culturalContext:'The record challenged the assumption that commercially released rap had to remain party music.',sound:'Sparse electronic rhythm, tense synth figure and narrative verses keep attention on the words.',impact:'It established social observation as a central possibility in recorded hip-hop.',then:'Its realism distinguished it sharply from the celebratory records that first brought rap to radio.',now:'It remains a reference for journalism-like storytelling in hip-hop.',artistContext:'The group came from a culture built in live performance, while the record foregrounded Melle Mel’s writing and voice.',lyricsMeaning:'Environmental pressure is shown as cumulative: broken infrastructure becomes emotional and social crisis.',politicalMoment:'Deindustrialization and urban policy concentrated risk in Black and Latino neighborhoods.',sources:['Library of Congress National Recording Registry','Smithsonian NMAAHC'],relatedTimeTravelDestinations:destinations('new-york-1979'),...links('Grandmaster Flash and the Furious Five','The Message')},
  {id:'99-luftballons-1983',title:'99 Luftballons',artist:'Nena',year:1983,decade:1980,country:'West Germany',city:'West Berlin',genre:'New wave',archiveLabel:'COLD WAR / NUCLEAR FEAR',accent:'blue',summary:'A bright pop song that imagines accidental escalation from harmless balloons to nuclear war.',themes:['nuclear anxiety','miscommunication','escalation'],historicalContext:'NATO’s missile deployment and mass peace protests made nuclear war feel immediate in divided Germany.',culturalContext:'Its international success showed that German-language pop could carry a specifically European Cold War anxiety into global charts.',sound:'Buoyant new wave energy makes the catastrophic narrative more unsettling.',impact:'It became one of the defining pop representations of accidental nuclear escalation.',then:'Listeners heard it inside active debates about missiles and peace movements.',now:'Its scenario feels newly relevant whenever automated systems and military suspicion dominate public debate.',artistContext:'Nena became the most globally visible act associated with the Neue Deutsche Welle boom.',lyricsMeaning:'A small, misread event becomes catastrophe because military systems assume threat and reward escalation.',politicalMoment:'Germany sat at the geographic center of nuclear confrontation between NATO and the Warsaw Pact.',sources:['Haus der Geschichte','German Historical Museum'],relatedTimeTravelDestinations:[],...links('Nena','99 Luftballons')},
  {id:'sunday-bloody-sunday-1983',title:'Sunday Bloody Sunday',artist:'U2',year:1983,decade:1980,country:'Ireland',city:'Dublin',genre:'Rock',archiveLabel:'NORTHERN IRELAND / ANTI-VIOLENCE',accent:'cream',summary:'A martial-sounding song that insists it is not a rebel anthem.',themes:['sectarian violence','grief','refusal'],historicalContext:'The Troubles had produced years of bombings, killings, imprisonment and political deadlock in Northern Ireland and Britain.',culturalContext:'Live performance required the band to repeatedly clarify its rejection of sectarian alignment.',sound:'March-like drums, violin and urgent guitar borrow the sound of conflict while arguing against it.',impact:'It became one of U2’s defining political songs and a model for arena-scale moral address.',then:'Its title carried the memory of multiple events known as Bloody Sunday, making interpretation politically charged.',now:'It is remembered as anti-violence, though listeners still debate the risks of simplifying historical conflict.',artistContext:'U2 were moving from post-punk origins toward an international, explicitly moral public voice.',lyricsMeaning:'The words describe shock and exhaustion, asking how long communities must repeat cycles of retaliation.',politicalMoment:'National identity, civil rights, policing and armed struggle were intertwined in the Northern Ireland conflict.',sources:['CAIN Archive at Ulster University','U2 official archive'],relatedTimeTravelDestinations:[],...links('U2','Sunday Bloody Sunday')},
  {id:'two-tribes-1984',title:'Two Tribes',artist:'Frankie Goes to Hollywood',year:1984,decade:1980,country:'United Kingdom',city:'Liverpool / London',genre:'Synth-pop',archiveLabel:'NUCLEAR WAR / MEDIA SPECTACLE',accent:'red',summary:'A maximal pop production that turns superpower confrontation into frightening entertainment.',themes:['Cold War','propaganda','spectacle'],historicalContext:'Nuclear anxiety remained high after renewed missile deployment and aggressive rhetoric between the United States and Soviet Union.',culturalContext:'The record’s videos and marketing collapsed politics, advertising and provocation into one media event.',sound:'Huge programmed drums, orchestral synth layers and spoken civil-defense references.',impact:'It showed how dance-pop could absorb geopolitical fear without surrendering commercial scale.',then:'The song’s imagery was instantly connected to Reagan, Soviet leadership and nuclear confrontation.',now:'It reads as both period satire and a warning about packaging conflict as entertainment.',artistContext:'The group and producer Trevor Horn used studio excess and media controversy as artistic material.',lyricsMeaning:'Human life is reduced to a game between blocs; the language of competition hides the stakes.',politicalMoment:'The Cold War was represented through civil-defense media, television and the constant possibility of escalation.',sources:['British Film Institute','Imperial War Museums'],relatedTimeTravelDestinations:[],...links('Frankie Goes to Hollywood','Two Tribes')},
  {id:'peremen-1986',title:'Peremen!',artist:'Kino',year:1986,decade:1980,country:'Soviet Union',city:'Leningrad / Moscow',genre:'Russian rock',archiveLabel:'PERESTROIKA / CHANGE',accent:'olive',summary:'A demand for change that outgrew the film and scene from which it emerged.',themes:['change','generational desire','agency'],historicalContext:'Perestroika and glasnost were loosening parts of Soviet public culture while political and economic uncertainty deepened.',culturalContext:'The song was not a policy program, but listeners made its refrain politically symbolic.',sound:'Direct new-wave guitar, steady pulse and Viktor Tsoi’s restrained vocal authority.',impact:'It became one of the most recognizable songs associated with late Soviet change.',then:'Young audiences heard it as a statement of generational impatience.',now:'Its reuse in later protests shows how songs can escape their original moment and acquire new political lives.',artistContext:'Kino grew from the Leningrad rock-club environment into mass cultural visibility.',lyricsMeaning:'The words demand change from within everyday life rather than describing a specific reform platform.',politicalMoment:'Official institutions were opening unevenly, creating both hope and instability.',sources:['Garage Museum archive','Wilson Center Digital Archive'],relatedTimeTravelDestinations:destinations('berlin-1989'),...links('Kino','Peremen')},
  {id:'fight-the-power-1989',title:'Fight the Power',artist:'Public Enemy',year:1989,decade:1980,country:'United States',city:'New York',genre:'Hip-hop',archiveLabel:'RACE / PUBLIC SPACE',accent:'red',summary:'A dense, confrontational soundtrack for refusing cultural and political deference.',themes:['racism','cultural authority','resistance'],historicalContext:'The song was created for Spike Lee’s Do the Right Thing, a film centered on race, policing and neighborhood conflict.',culturalContext:'Its samples construct an alternative archive of Black music while the lyrics dispute who becomes a national hero.',sound:'Layered samples, sirens, breaks and forceful group vocals create organized overload.',impact:'It became a defining political recording in hip-hop and American cinema.',then:'The song and film entered debates over whether depicting anger exposed violence or encouraged it.',now:'It remains a reference for protest against racism and police power.',artistContext:'Public Enemy treated the studio, stage and visual identity as coordinated political communication.',lyricsMeaning:'The song asks listeners to reject inherited cultural authority and confront power directly.',politicalMoment:'Racial segregation, police violence and disputes over representation shaped urban American politics.',sources:['Library of Congress National Recording Registry','Smithsonian NMAAHC'],relatedTimeTravelDestinations:destinations('new-york-1979'),...links('Public Enemy','Fight the Power')},
  {id:'wind-of-change-1990',title:'Wind of Change',artist:'Scorpions',year:1990,decade:1990,country:'West Germany',city:'Moscow / Berlin',genre:'Rock ballad',archiveLabel:'1989 / TRANSFORMATION',accent:'blue',summary:'A rock ballad that converted the emotional memory of late Cold War change into a global hit.',themes:['political change','hope','East-West encounter'],historicalContext:'Written after the band’s experiences in Moscow and released as communist governments across Europe were collapsing.',culturalContext:'Its success helped establish one simplified, hopeful soundtrack for a transformation that was far more uneven.',sound:'Whistled motif, slow build and arena-rock dynamics make geopolitical optimism intimate and memorable.',impact:'It became globally associated with the end of the Cold War.',then:'Audiences received it during a period of genuine uncertainty about what post-Cold War Europe would become.',now:'It carries nostalgia for 1989 while inviting questions about which hopes were realized.',artistContext:'Scorpions were a West German hard-rock band with unusual popularity in the Soviet Union.',lyricsMeaning:'The lyric imagines political change as a natural wind moving across borders and generations.',politicalMoment:'The Berlin Wall had opened, German reunification was underway and the Soviet order was weakening.',sources:['Haus der Geschichte','Scorpions official archive'],relatedTimeTravelDestinations:destinations('berlin-1989'),...links('Scorpions','Wind of Change')},
  {id:'unfinished-sympathy-1991',title:'Unfinished Sympathy',artist:'Massive Attack',year:1991,decade:1990,country:'United Kingdom',city:'Bristol',genre:'Trip-hop / soul',archiveLabel:'POST-INDUSTRIAL CITY / HYBRID SOUND',accent:'orange',summary:'A cinematic song built from club culture, soul, sampling and Bristol’s multicultural scene.',themes:['desire','emotional exposure','urban movement'],historicalContext:'British cities were shaped by deindustrialization, racial politics and new club cultures connecting local and imported sounds.',culturalContext:'The track resists a narrow political reading, but its form records cultural mixture and the social infrastructure of a specific city.',sound:'Breakbeats, orchestral strings, bass and Shara Nelson’s vocal create tension between intimacy and scale.',impact:'It became a landmark for the Bristol sound and 1990s electronic music.',then:'It sounded neither like conventional soul nor like existing dance categories.',now:'It is heard as proof that musical hybridity can define a city internationally.',artistContext:'Massive Attack emerged from the Wild Bunch sound-system network rather than a conventional rock-band model.',lyricsMeaning:'The words describe emotional incompleteness and the risk of allowing another person access to the self.',politicalMoment:'The song’s politics lie less in slogans than in who could make a new British sound from diasporic, club and pop traditions.',sources:['Bristol Archives','British Library sound archive'],relatedTimeTravelDestinations:[],...links('Massive Attack','Unfinished Sympathy')},
  {id:'smells-like-teen-spirit-1991',title:'Smells Like Teen Spirit',artist:'Nirvana',year:1991,decade:1990,country:'United States',city:'Seattle',genre:'Grunge',archiveLabel:'YOUTH / MASS CULTURE',accent:'cream',summary:'A cryptic rock single that the music industry turned into a generational symbol.',themes:['alienation','irony','youth identity'],historicalContext:'Alternative scenes were moving into major-label distribution as youth marketing became increasingly sophisticated.',culturalContext:'The distance between the song’s fragmented words and the certainty of its “generation” label is crucial to its history.',sound:'Quiet-loud dynamics, a blunt guitar figure and a vocal moving from mumble to rupture.',impact:'It shifted the commercial center of rock and intensified attention on Seattle’s local scene.',then:'Its success surprised the band and record industry, producing a level of representation no local scene could control.',now:'It is canonized as a 1990s anthem, often smoothing away its irony and discomfort.',artistContext:'Nirvana brought punk ethics and underground references into a mass-market system they distrusted.',lyricsMeaning:'There is no single political thesis; boredom, self-mockery and refusal make the song resistant to clean explanation.',politicalMoment:'The end of the Cold War did not produce a clear new identity for young people in the United States.',sources:['Museum of Pop Culture Seattle','Library of Congress'],relatedTimeTravelDestinations:[],...links('Nirvana','Smells Like Teen Spirit')},
  {id:'killing-in-name-1992',title:'Killing in the Name',artist:'Rage Against the Machine',year:1992,decade:1990,country:'United States',city:'Los Angeles',genre:'Rap metal',archiveLabel:'POLICE POWER / RACISM',accent:'red',summary:'A repetitive, escalating accusation connecting racist violence to state authority.',themes:['police violence','institutional racism','refusal'],historicalContext:'Released after the beating of Rodney King and the 1992 Los Angeles uprising following the acquittal of police officers.',culturalContext:'The song’s profanity and directness made censorship and radio restriction part of its public meaning.',sound:'A heavy guitar riff, hip-hop-informed rhythm and an extended vocal escalation.',impact:'It became a durable protest song far beyond its original US context.',then:'Its political references were immediate to audiences watching the Los Angeles crisis.',now:'It is repeatedly revived in protests against police violence and authoritarian power.',artistContext:'The group explicitly joined radical political messaging to hard-rock spectacle.',lyricsMeaning:'The lyric argues that white-supremacist power can reproduce itself inside institutions presented as neutral.',politicalMoment:'Video evidence of police violence collided with legal impunity and long-standing inequality in Los Angeles.',sources:['UCLA Film & Television Archive','Los Angeles Public Library'],relatedTimeTravelDestinations:[],...links('Rage Against the Machine','Killing in the Name')},
  {id:'changes-1998',title:'Changes',artist:'2Pac',year:1998,decade:1990,country:'United States',city:'Los Angeles',genre:'Hip-hop',archiveLabel:'RACE / POVERTY / MEMORY',accent:'orange',summary:'A posthumous single framing racism, poverty and violence as structures that survive individual success.',themes:['racism','poverty','change'],historicalContext:'Released after Tupac Shakur’s death, the track compiled earlier vocals into a new late-1990s production.',culturalContext:'Its posthumous construction matters: audiences heard a voice from an earlier moment reorganized as memorial and diagnosis.',sound:'A familiar piano interpolation and clear verse-chorus structure make social commentary highly accessible.',impact:'It became one of the artist’s most widely recognized songs internationally.',then:'The release participated in the rapid construction of Tupac as a symbol after his death.',now:'It remains a common entry point to discussions of continuity in American racial inequality.',artistContext:'Tupac’s public image moved between political inheritance, vulnerability, confrontation and commercial mythology.',lyricsMeaning:'The song describes individual desire for change colliding with institutions and cycles larger than one person.',politicalMoment:'Mass incarceration, police violence and concentrated poverty shaped Black urban life in the 1990s.',sources:['Smithsonian NMAAHC','California African American Museum'],relatedTimeTravelDestinations:[],...links('2Pac','Changes')},
  {id:'clandestino-1998',title:'Clandestino',artist:'Manu Chao',year:1998,decade:1990,country:'France / Spain',city:'Paris / Madrid',genre:'Latin alternative',archiveLabel:'MIGRATION / BORDERS',accent:'olive',summary:'A quiet, globally circulating song narrated from the position of an undocumented migrant.',themes:['migration','borders','invisibility'],historicalContext:'European integration coincided with increasingly policed external borders and public debate over migration.',culturalContext:'The song’s multilingual album environment refuses the idea that culture fits neatly inside one nation.',sound:'Sparse guitar, looped rhythm and street-recording textures create intimacy rather than spectacle.',impact:'It became a central recording in transnational alternative music.',then:'Its narrator gave migration politics a first-person emotional frame for broad audiences.',now:'The song remains relevant as border regimes and forced migration intensify.',artistContext:'Manu Chao developed a mobile, multilingual practice from punk, Latin American music, radio and street sound.',lyricsMeaning:'The narrator is officially invisible—named illegal by the border while living an ordinary human life.',politicalMoment:'The Schengen era changed movement inside Europe while hardening distinctions between authorized and unauthorized migrants.',sources:['Musée national de l’histoire de l’immigration','European migration archives'],relatedTimeTravelDestinations:[],...links('Manu Chao','Clandestino')},
  {id:'chop-suey-2001',title:'Chop Suey!',artist:'System of a Down',year:2001,decade:2000,country:'United States / Armenian diaspora',city:'Los Angeles',genre:'Alternative metal',archiveLabel:'MORAL JUDGMENT / 2001',accent:'blue',summary:'A volatile song about death, judgment and the different value society assigns to lives.',themes:['death','judgment','self-righteousness'],historicalContext:'Released weeks before the September 11 attacks, it entered a radically changed media environment and was among songs treated cautiously by some broadcasters.',culturalContext:'The group’s Armenian-American identity and political work made listeners attentive to history even when a song was not a literal policy statement.',sound:'Extreme shifts between rapid verses, heavy riffs and choral passages.',impact:'It became a defining heavy-music single of the early 2000s.',then:'Its release timing changed its media reception in ways the song could not have anticipated.',now:'It is remembered for both formal unpredictability and a debate about who receives compassion after death.',artistContext:'System of a Down connected Los Angeles metal, Armenian diasporic identity and explicit activism.',lyricsMeaning:'The song questions why some deaths are moralized and condemned while others are sanctified.',politicalMoment:'After September 11, US media, war politics and acceptable public speech changed rapidly.',sources:['Armenian American Museum','Broadcast media archives'],relatedTimeTravelDestinations:[],...links('System of a Down','Chop Suey')},
  {id:'strange-fruit-1939',title:'Strange Fruit',artist:'Billie Holiday',year:1939,decade:1930,country:'United States',city:'New York',genre:'Jazz / protest',archiveLabel:'LYNCHING / WITNESS',accent:'red',summary:'A stark performance that forced the terror of racial lynching into a nightclub and recording studio.',themes:['racial terror','mourning','witness'],historicalContext:'Lynching and racial segregation remained entrenched in the United States while federal anti-lynching legislation repeatedly failed.',culturalContext:'Performance conditions at Café Society made the song a ritual of attention rather than background entertainment.',sound:'Sparse accompaniment and Holiday’s controlled phrasing keep every image exposed.',impact:'It became one of the foundational protest recordings in American music.',then:'The song was powerful, controversial and difficult for the commercial music industry to handle.',now:'It remains a disturbing document of how art can name violence that institutions normalize.',artistContext:'Billie Holiday transformed Abel Meeropol’s text through phrasing that made public horror feel immediate and personal.',lyricsMeaning:'Pastoral imagery is deliberately overturned to reveal Black bodies subjected to racial violence.',politicalMoment:'Jim Crow law, white-supremacist terror and institutional inaction structured American life.',sources:['Library of Congress','Smithsonian NMAAHC'],relatedTimeTravelDestinations:[],...links('Billie Holiday','Strange Fruit')},
  {id:'change-is-gonna-come-1964',title:'A Change Is Gonna Come',artist:'Sam Cooke',year:1964,decade:1960,country:'United States',city:'Los Angeles',genre:'Soul',archiveLabel:'CIVIL RIGHTS / HOPE',accent:'cream',summary:'A personal spiritual and a civil-rights statement held together in one orchestral soul recording.',themes:['hope','racism','endurance'],historicalContext:'Released in the year of the Civil Rights Act, after years of organizing against segregation and racial violence.',culturalContext:'Its authority comes from connecting public struggle to exhaustion, faith and individual vulnerability.',sound:'Orchestral arrangement, deliberate pacing and Cooke’s gospel-shaped delivery.',impact:'It became one of the most enduring musical expressions associated with the civil-rights movement.',then:'The song carried hope without pretending that legal change had ended danger or inequality.',now:'It is repeatedly revived during struggles for racial justice and democratic change.',artistContext:'Sam Cooke moved between gospel tradition, pop success and growing engagement with Black autonomy in the music business.',lyricsMeaning:'The narrator’s certainty that change will come coexists with fear, isolation and repeated setbacks.',politicalMoment:'Civil-rights victories were being won against violent resistance and deep structural inequality.',sources:['Library of Congress National Recording Registry','Smithsonian NMAAHC'],relatedTimeTravelDestinations:[],...links('Sam Cooke','A Change Is Gonna Come')},
  {id:'ohio-1970',title:'Ohio',artist:'Crosby, Stills, Nash & Young',year:1970,decade:1970,country:'United States',city:'Los Angeles',genre:'Rock / protest',archiveLabel:'KENT STATE / ANTI-WAR',accent:'red',summary:'An unusually rapid musical response to the killing of students at Kent State University.',themes:['state violence','Vietnam War','student protest'],historicalContext:'National Guard troops killed four students during a protest against the expansion of the Vietnam War into Cambodia.',culturalContext:'The speed from event to recording and radio circulation made the song function almost like breaking news.',sound:'Raw electric guitars and repeated names turn urgency into memory.',impact:'It became one of the defining anti-war recordings of the Nixon era.',then:'Listeners encountered the song while the event and its political arguments were still unfolding.',now:'It remains a model for immediate artistic response to state violence.',artistContext:'Neil Young wrote the song for a successful group already associated with countercultural audiences.',lyricsMeaning:'The words accuse political leadership and insist that the dead be named rather than absorbed into abstraction.',politicalMoment:'Campus protest, the Vietnam War and aggressive state response were reshaping American political life.',sources:['Kent State University archives','Library of Congress'],relatedTimeTravelDestinations:[],...links('Crosby Stills Nash & Young','Ohio')},
  {id:'whats-going-on-1971',title:'What’s Going On',artist:'Marvin Gaye',year:1971,decade:1970,country:'United States',city:'Detroit',genre:'Soul',archiveLabel:'WAR / CITY / COMPASSION',accent:'olive',summary:'A gentle question that opened onto war, policing, ecology and urban crisis.',themes:['Vietnam War','policing','social repair'],historicalContext:'The United States was divided by the Vietnam War while Black communities faced police violence and economic inequality.',culturalContext:'The song replaced Motown’s usual romantic focus with a social conversation without abandoning beauty or accessibility.',sound:'Layered vocals, flowing bass and orchestration create a communal rather than confrontational appeal.',impact:'It expanded what a mainstream soul album could address.',then:'Its political scope initially concerned parts of the Motown organization before the single became a major success.',now:'It is heard as both period document and an enduring plea for social attention.',artistContext:'Marvin Gaye used his commercial position to demand greater artistic control and address public life.',lyricsMeaning:'The narrator asks people to see one another through conflict and to recognize violence as a shared social failure.',politicalMoment:'War abroad and inequality at home were increasingly understood as connected moral crises.',sources:['Motown Museum','Library of Congress'],relatedTimeTravelDestinations:[],...links('Marvin Gaye',"What's Going On")},
  {id:'born-in-usa-1984',title:'Born in the U.S.A.',artist:'Bruce Springsteen',year:1984,decade:1980,country:'United States',city:'New Jersey',genre:'Rock',archiveLabel:'VIETNAM VETERANS / MISREAD ANTHEM',accent:'blue',summary:'A bitter veteran’s story packaged in a chorus repeatedly mistaken for uncomplicated patriotism.',themes:['Vietnam veterans','economic abandonment','national identity'],historicalContext:'Public memory of the Vietnam War was shifting while deindustrialization and patriotic political imagery shaped the Reagan era.',culturalContext:'The distance between the triumphant sound and the bleak verses became a lesson in how audiences hear only the chorus they expect.',sound:'Explosive drums, synthesizer and a compressed refrain built for arenas.',impact:'It became both a blockbuster and one of popular music’s best-known cases of political misreading.',then:'Politicians and audiences sometimes treated it as celebration despite its narrative of abandonment.',now:'It remains central to arguments about patriotism, class and selective listening.',artistContext:'Springsteen’s writing repeatedly centered working lives, damaged institutions and the gap between national promises and lived reality.',lyricsMeaning:'A Vietnam veteran returns to limited work and limited support; birthplace is presented as burden as much as pride.',politicalMoment:'Reagan-era optimism coexisted with industrial decline and unresolved consequences of the Vietnam War.',sources:['Bruce Springsteen Archives','National Museum of American History'],relatedTimeTravelDestinations:[],...links('Bruce Springsteen','Born in the U.S.A.')},
  {id:'fuck-tha-police-1988',title:'Fuck tha Police',artist:'N.W.A',year:1988,decade:1980,country:'United States',city:'Los Angeles',genre:'Hip-hop',archiveLabel:'POLICING / INSTITUTIONAL RACISM',accent:'red',summary:'A staged courtroom fantasy indicting racist and violent policing in Los Angeles.',themes:['police violence','racism','anger'],historicalContext:'Black communities in Los Angeles faced aggressive policing practices years before the Rodney King beating became globally visible.',culturalContext:'Official condemnation and law-enforcement pressure became part of the song’s history and reach.',sound:'Hard drums, samples and alternating voices structure the track like testimony.',impact:'It made police violence an unavoidable subject in mainstream debate about hip-hop.',then:'Authorities treated the record as a threat while many listeners recognized it as an account of lived experience.',now:'It is repeatedly revisited during protests against police brutality.',artistContext:'N.W.A converted local detail, confrontation and media controversy into a new national visibility for West Coast rap.',lyricsMeaning:'The fictional trial reverses institutional power and lets those policed judge the police.',politicalMoment:'The militarization of policing and the war on drugs concentrated state power in Black neighborhoods.',sources:['California African American Museum','Los Angeles Public Library'],relatedTimeTravelDestinations:[],...links('N.W.A','Fuck tha Police')},
  {id:'alright-2015',title:'Alright',artist:'Kendrick Lamar',year:2015,decade:2010,country:'United States',city:'Los Angeles',genre:'Hip-hop',archiveLabel:'BLACK LIVES MATTER / SURVIVAL',accent:'cream',summary:'A song in which collective reassurance exists beside depression, temptation and police violence.',themes:['survival','racial justice','hope'],historicalContext:'The Black Lives Matter movement was reshaping public debate after multiple police killings of Black Americans.',culturalContext:'Crowds turned the chorus into a protest chant, giving the recording a public function beyond the album.',sound:'Jazz-inflected production, layered voices and a floating refrain balance anxiety with release.',impact:'It became one of the defining protest songs of the 2010s.',then:'Its meaning expanded through demonstrations and collective performance.',now:'It remains a model for hope that does not deny structural violence or personal struggle.',artistContext:'Kendrick Lamar used narrative, character and historical memory to examine Black life in Compton and the United States.',lyricsMeaning:'The promise of being alright is not naïve certainty; it is a survival practice repeated against evidence of danger.',politicalMoment:'Grassroots organizing challenged police violence, racial inequality and official narratives about public safety.',sources:['Smithsonian NMAAHC','National Museum of African American Music'],relatedTimeTravelDestinations:[],...links('Kendrick Lamar','Alright')},
  {id:'this-is-america-2018',title:'This Is America',artist:'Childish Gambino',year:2018,decade:2010,country:'United States',city:'Atlanta',genre:'Hip-hop / trap',archiveLabel:'GUN VIOLENCE / SPECTACLE',accent:'orange',summary:'A song and video built around abrupt switches between entertainment, violence and distraction.',themes:['gun violence','racism','spectacle'],historicalContext:'Mass shootings, police violence and viral media were central to American public life.',culturalContext:'The video is essential to the work: choreography and visual references force attention to move between performance and background violence.',sound:'Gospel-derived passages are interrupted by sparse, threatening trap sections.',impact:'It became a global reference for discussing violence and media attention in the United States.',then:'Its dense visual symbolism generated immediate debate and competing interpretations.',now:'It remains a snapshot of an attention economy in which violence and entertainment circulate together.',artistContext:'Donald Glover used the Childish Gambino project across music, television and performance to examine American identity.',lyricsMeaning:'The repeated phrase refuses explanation; it presents contradiction as the condition of American life.',politicalMoment:'Digital platforms made violence visible while also turning it into endlessly replaced content.',sources:['National Museum of African American History and Culture','Museum of the Moving Image'],relatedTimeTravelDestinations:[],...links('Childish Gambino','This Is America')}
]

// A focused, independently written guide to songs appearing in Rolling Stone's
// 2021 edition of “The 500 Greatest Songs of All Time”. The editorial copy above
// is original to Hear the World; only the selection and known ranks reference the list.
const rollingStoneIds = new Set([
  'street-fighting-man-1968','revolution-1968','say-it-loud-1968',
  'revolution-not-televised-1971','get-up-stand-up-1973','zombie-1976',
  'god-save-queen-1977','heroes-1977','good-times-1979','rappers-delight-1979',
  'the-message-1982','sunday-bloody-sunday-1983','fight-the-power-1989',
  'unfinished-sympathy-1991','smells-like-teen-spirit-1991','killing-in-name-1992',
  'chop-suey-2001','strange-fruit-1939','change-is-gonna-come-1964','ohio-1970',
  'whats-going-on-1971','born-in-usa-1984','fuck-tha-police-1988','alright-2015',
  'this-is-america-2018'
])

const rollingStoneRanks:Record<string,number> = {
  'fight-the-power-1989':2,
  'change-is-gonna-come-1964':3,
  'smells-like-teen-spirit-1991':5,
  'whats-going-on-1971':6,
  'strange-fruit-1939':21,
  'heroes-1977':23,
  'alright-2015':45,
  'the-message-1982':51
}

export const rollingStoneCatalog: CatalogSong[] = musicCatalog
  .filter(song=>rollingStoneIds.has(song.id))
  .map(song=>({...song,rollingStoneRank:rollingStoneRanks[song.id]}))

export const punkJourney: JourneyNode[] = [
  {id:'london-1977',city:'London',year:1977,label:'Punk as rupture',reason:'DIY production and open confrontation with the British establishment.'},
  {id:'warsaw-1982',city:'Warsaw',year:1982,label:'Punk under pressure',reason:'A recognizable sound adapted through censorship, scarcity and copied tapes.'},
  {id:'berlin-1985',city:'Berlin',year:1985,label:'Two cities, two scenes',reason:'Experimental, industrial and punk cultures develop on both sides of the Wall.'},
  {id:'moscow-1988',city:'Moscow',year:1988,label:'Rock moves into public view',reason:'Glasnost alters the distance between unofficial culture and mass audiences.'}
]

export const todayFacts = [
  {date:'25 SEP 1976',title:'The musicians who became U2 meet in Dublin',text:'After Larry Mullen Jr. posted a notice at Mount Temple school, the group’s first gathering took place in his family kitchen in Artane.'},
  {date:'25 SEP 1980',title:'Led Zeppelin lose John Bonham',text:'The drummer’s death at 32 ended one of rock’s defining lineups; the surviving members announced that they could not continue as before.'}
]
